bool request
---
float32 robot_x
float32 robot_y
float32 robot_theta
float32 robot_radio
float32 robot_max_advance
float32 robot_turn_angle
int32 laser_num_sensors
float32 laser_origin
float32 laser_range
float32 laser_value
string world_name
bool noise
bool run
float32 light_x
float32 light_y
int32 behavior
int32 steps
